### ISSUE TITLE
ipython startup scripts won't load

### ISSUE THREAD

**Issue by jaybubs** [jupyter-server/enterprise_gateway#1060]
Enterprise Gateway version: 2.6.0 (helm)

Ordinarily users put any startup scripts in their .ipython folder (eg /home/jovyan/.ipython/default_profile/startup) and they get executed during the kernel startup, however this is not the case when jupyter enterprise gateway(jeg) is used.

Some things I was able to find out:
When running a normal kernel `who` outputs `NamespaceMagics get_ipython`
When running jeg `who` outputs `Interactive namespace is empty`

Both in a normal and jeg kernel the output of `get_ipython().profile_dir.startup_dir` point correctly to `/home/jovyan/.ipython/default_profile/startup`

This got me digging some more until I backtraced it to `launch_ipykernel.py` where we have the following bits:
```python
def start_ipython(namespace, cluster_type="spark", **kwargs):
    from IPython import embed_kernel
    #other code processing namespace
    embed_kernel(local_ns=namespace, **kwargs)
```

Now the [embed_kernel function](https://github.com/ipython/ipython/blob/6d40fd892d5268a91a514d9dd532ba097dd345aa/IPython/__init__.py#L68) is then documented saying that:
```
    If you don't want the kernel to initialize the namespace
    from the scope of the surrounding function,
    and/or you want to load full IPython configuration,
    you probably want `IPython.start_kernel()` instead.
```
likewise, the complimentary [start_kernel function](https://github.com/ipython/ipython/blob/6d40fd892d5268a91a514d9dd532ba097dd345aa/IPython/__init__.py#L125) mentions:
```
    `IPython.embed_kernel()` puts a shell in a particular calling scope,
    such as a function or method for debugging purposes,
    which is often not desirable.
    `start_kernel()` does full, regular IPython initialization,
    including loading startup files, configuration, etc.
    much of which is skipped by `embed()`.
```

which then lead me to conclude the startup scripts are not loading precisely because it's using the "wrong" function. Digging even further into the code got me extremely confused because it's one hell of a rabbit hole.

I was keeping an eye out on what start_kernel does differently to embed_kernel, specifically looking for some sort of "glob_startup_folder" functionality but no luck thus far.

I did try a simple substitution of replacing the embed_kernel with start_kernel in the `launch_ipykernel.py` file, skipping out on the namespace or so, but that just resulted in 1) redirecting the function to launch_new_instance (as documented), but more importantly 2) kwargs processing error, where none of the jeg flags get processed `unrecognized arguments --kernel-id --port-range etc etc`

So that's it in a nutshell, any ideas/workarounds?

**Comment by rahul26goyal** [comment]
Thanks a lot @jaybubs  for open the issue and providing such great details. 

I had faced similar issue sometime back when I wanted to enable a kernel magic at start-up and the workaround which worked for me was passing those list of magics to `start_ipython` method as defined below:

 ```
 extensions = [<list of packages to load>] 
 start_ipython(locals(), cluster_type=cluster_type, connection_file=connection_file, extensions=extensions, ...)
```
please give this a try and see if it helps unblock your immediate needs. 
cc: @kevin-bates

**Comment by kevin-bates** [comment]
Hi @jaybubs.

The `embed_kernel` approach has been in place since EG was created in 2017. At that time, we were focused on ensuring a Spark Context could be initialized w/o user intervention and the developer chose to use `embed_kernel` to accomplish that kind of functionality.  The "namespace logic" was significantly reworked when [support for Dask was added](https://github.com/jupyter-server/enterprise_gateway/pull/529), since it didn't need Spark.  

To be perfectly honest with you, this is not an area I've spent any significant time with, primarily because things haven't come up, and it deals with a level of Python to which I haven't been familiar - given Python was new to me when we started EG.  I would love to see this area cleaned up and all of its "rabbit holes" filled, but I'm probably not the best person to tackle that.  So, until this project gets more community support, I'm not sure I (we) have a good answer here.  I'm sorry.

**Comment by jaybubs** [comment]
@rahul26goyal So I had no luck implementing your solution as described. I did dig thru pages of docs and code only to arrive at...well nothing useful really - there was no magic associated with startup scripts or the likes. But it did manage to accidentally prompt me to search and find the correct thing. I forgot what exactly it was but basically I was originally accidentally _almost_ there. Basically what I did find out is that [the ipython start_kernel](https://github.com/ipython/ipython/blob/6d40fd892d5268a91a514d9dd532ba097dd345aa/IPython/__init__.py#L125) method mentions `"start_kernel is deprecated since IPython 8.0, use from `ipykernel.kernelapp.launch_new_instance`"` and then launches it
```python
    from ipykernel.kernelapp import launch_new_instance
    return launch_new_instance(argv=argv, **kwargs)
```
like so. Following this down leads to [this](https://github.com/ipython/ipykernel/blob/7717f2ccc774ec9a8378e8e279e61218c987d28e/ipykernel/kernelapp.py#L712) chunk of code:
```python
launch_new_instance = IPKernelApp.launch_instance


def main():
    """Run an IPKernel as an application"""
    app = IPKernelApp.instance()
    app.initialize()
    app.start()
```
now at this point i actually started following thru and examining the sourcecode for `BaseIPythonApplication, InteractiveShellApp, ConnectionFileMixin` which are all dependants of `IPKernelApp`. But this was a mistake because I guess i just don't know how to correctly read jupyter code... Fortunately this is where i decided to google a bit more and came across [this gist](https://gist.github.com/lazywhite/606e6a47ed258013a9d276ec9d4c9815#file-launch_ipykernel-py-L351) mentioned previously in ... [this very repo!](https://github.com/jupyter-server/enterprise_gateway/issues/795). Turns out it was _the_ solution! Virtually the same thing as in the code snip above.

So for completion sake, the final implementation looks like this:
```python
# ...../kernel-launchers/python/scripts/launch_ipykernel.py
# other code
def start_ipython(namespace,cluster_type="spark", **kwargs):
    # import embed_kernel is removed and replaced by:
    from ipykernel.kernelapp import IPKernelApp as IPKA
    # to_delete, initialize_namespace, for k in delete ... are all preserved
    # embed_kernel is removed and replaced by:
    if IPKA.initialized():
        app = IPKA.instance()
    else:
        app = IPKA.instance(**kwargs)
        app.initialize([])
        app.kernel.user_ns = namespace
        app.start()
# other code
````

@kevin-bates pardon my ignorance, i've zero idea about spark, yarn, dask or anything else beyond vanilla k8s when it comes to orchestration. So I can't really tell whether this would potentially break in those environments for whatever reasons. But if someone is willing to spin this little modification up in those environments to see if it does work, it might be worth considering 'upgrading' the code like so? Or at least give it a side mention somewhere in the docs. I do remember needing to refer to elyra docs at one point just to hook up jeg to singleuser...

In any case, it's an impressive piece of work you've done, especially given that you said it was all new to you!

So yea, much obliged for the help, and conversly i hope this snip helps someone too!

**Comment by kevin-bates** [comment]
@jaybubs - thank you for your informative response - it is much appreciated!  We're happy you're moving forward.

So, this information, coupled with the gist you referenced (back into this repo!), I think we might have enough to go on to introduce some _alternate_ forms of python-based kernels or meta-kernels.  In addition, when the `--RemoteProcessProxy.spark-context-initialization-mode` indicates `none` (the default), we could skip the `embed_kernel()` call since Spark context initialization isn't necessary and those uses would be able to leverage startup scripts.  (Although it would be nice, and we should explore the ability, to allow spark-based invocations to leverage those same scripts - which appears to not be available via `embed_kernel()`.  [note: need to go understand the differences between `embed_kernel()` and `start()`.])

I had (falsely) hoped the previous changes would be contributed, but I don't see that happening at this point.

@rahul26goyal - do you think we can enhance the launcher to accept additional parameters to address meta-kernels?  Seems like we'd also need the class name of the meta-kernel and I'm wondering if we could derive the kernel name from that class instance since it's likely just a default value (in order to limit the number of additional parameters, etc.). 

I'm also wondering if we should add a section to the [Developers Guide](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/developers/index.html) that includes little code snippets of these sorts.

**Comment by jaybubs** [comment]
@kevin-bates hey i got some minor useful updates, we're using the gateway in production, so it was a question of time before someone noticed

when a notebook/console is started, the startup scripts load just fine _but_ locals and globals get messed up - so it looks like they did not load in fact.
for example, by having `x=1` in a startup script the following block would fail, complaining x was never defined:
```python
%%time
x
```
Simply by punching in `locals()` and `globals()` you can see that there's a mismatch, and a cell like that is looking for the variables among logals.

After a bit of digging the solution turned out to be to simply forego passing namespace, our current launching function looks like so:
```python
# ...../kernel-launchers/python/scripts/launch_ipykernel.py
# other code
def start_k8s_ipython(cluster_type="spark", **kwargs):
    from ipykernel.kernelapp import IPKernelApp as IPKA
    if IPKA.initialized():
        app = IPKA.instance()
    else:
        app = IPKA.instance(**kwargs)
        app.initialize([])
        app.start()
# other code
if __name__ == "__main__":
    # other stuff
    # removing namespace, or in this case locals() from args
    start_k8s_ipython(cluster_type=cluster_type, connection_file=connection_file, ip=ip)
```

again, not sure how this would affect non-vanilla clusters, but as far as vanilla k8s, it works like a charm!

**Comment by kevin-bates** [comment]
Thanks @jaybubs - this is helpful information.  I don't currently have the bandwidth (or knowledge) to look into this at the moment.

When you say _vanilla k8s_ are you using the `KubernetesProcessProxy` in your `kernel.json` file but you don't use Spark?  I think the reason we use `embed_kernel()` and `locals()` is so that we can set up the SparkContext `sc` within the namespace of the kernel process.  

As I mentioned above, I suppose we could adopt this form of construction in cases where we know no SparkContext is necessary.

**Comment by jaybubs** [comment]
@kevin-bates i appreciate you taking the time to read my rants!

That's right, the process proxy is set as k8s, and we have no spark stuff running anywhere in the cluster. I inferred as much wrt embedding from your previous comment, and while i just straight up culled any sort of namespace code that's useful for spark, as you say for the more general implementation it could just be put behind one or two if statements - checking whether the context is spark, if not, forego injecting namespace.

There's probably other available `IPKA.instance` traitlets that might even be leveraged to have this available in spark (eg. `IPKA.instance().user_ns = namespace` was used in the gist mentioned above) and you might even be able to skip kernel embedding in that case. But my complaint about jupyter still stands, the documentation and source code is a total pain to crawl thru, so I can't blame you or anyone else really for not having the mood to sift thru that 😅. If you want I could bring over some of the changes I did to make it work on our end and incorporate it into yours?

**Comment by kevin-bates** [comment]
Yeah, I found it interesting to see the traitlets `SingletonConfigurable` pattern - which makes sense.  Thanks for the code snippet.  I think it would be good to introduce such a code path, but first I'd like to go understand the locals() and _embed v. start_ stuff a bit and see if other changes can be made, etc.

Thanks for your help.  I'm hoping I can ping you for a review.

**Comment by jaybubs** [comment]
Oh ye absolutely do ping, happy to help!
