### ISSUE TITLE
Is there any way to limit all kernel resources now?

### ISSUE THREAD

**Issue by LeeMoonCh** [jupyter-server/enterprise_gateway#1075]
## Description
If I use JEG to open a `python_distributed` kernel, is there any way to limit the resources used by the kernel?
For example:

>  I want the kernel to most use  5GB of memory and  2 cores. 
#770  It is restricted at k8s.

**Comment by kevin-bates** [comment]
Hi @LeeMoonCh,

> is there any way to limit the resources used by the kernel?

No, not at this time.  This would likely be addressed when the ecosystem introduces _parameterized kernels_, but it's been tough to get traction on that.

As you're aware, the  Kubernetes kernel environment can support resources like this because [each kernel is associated with a kernel-pod template file and because `KERNEL_`-prefixed envs can _flow_ from the client through EG to the kernel](https://github.com/jupyter-server/enterprise_gateway/blob/67683767656af1e41879c609159edfedcab3cfe3/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2#L63-L87), they can behave like parameters.

Given that `KERNEL_`-prefixed envs _flow_, and if you know how to start a process specifying these kinds of resources and those parameters can be specified on the command line, then you might be able to launch the kernel in that manner.  Since the default kernel launchers don't know that kind of thing, I would imagine this would require some kind of process wrapper or shell, but we don't provide such functionality outside of Kubernetes.  Sorry about that.

**Comment by LeeMoonCh** [comment]
Thank you! @kevin-bates  
I think I could do this by modifying the startup script. Passed through parameter variables.

**Comment by kevin-bates** [comment]
If you find a solution that fits nicely with the implementation please consider contributing it. It could provide a great datapoint relative to _parameterized kernels_.

**Comment by LeeMoonCh** [comment]
I think we can introduce cgroups to limit resource usage. This requires the model to include a pid. This idea is better implemented in jupyter server.
I'll give it a try locally now.
