### ISSUE TITLE
Spark driver and executor pods staying alive even after kernel switch to new kernel

### ISSUE THREAD

**Issue by vivekbhide** [jupyter-server/enterprise_gateway#1167]
## Description

While using `Spark Operator (Python)` kernel from EG, the Spark driver and executor pods continues to stay alive even after kernel is switched to different one in corresponding notebook. This don't seem to be case with other Kubernetes kernels like `Python on Kubernetes` where switching to a different kernel kills the pod for old kernel

### Setup - 

1. Create a duplicate `Spark Operator (Python)` called `Custom Spark Operator (Python)` on EG pod. Content of the kernel directory are identical. Purpose is to be able to switch between similar kernels which could very well be the real life scenario (two spark kernels with different set of libraries)

### Test Scenario - 

1. Create a Notebook with spark code
2. Select kernel `Custom Spark Operator (Python)`
3. Execute the notebook.
4. Switch the kernel to `Spark Operator (Python)`

### Expected result - 

1. Driver and executor pods for `Custom Spark Operator (Python)` should get deleted (meaning executor pods are deleted and driver pod is transitioned to `succeeded` and hence will be cleaned by garbage collection or manual removal) and a new driver pod is initiated for  `Spark Operator (Python)`

### Actual result - 
1. Pod for `Custom Spark Operator (Python)` continue to be in running state with new set of pod getting initiated for `Spark Operator (Python)`
2. Driver pod for `Custom Spark Operator (Python)` shows the shutdown signal log but doesn’t kill the pods

```
22/10/04 18:03:31 INFO DAGScheduler: Job 7 is finished. Cancelling potential speculative or zombie tasks for this job
22/10/04 18:03:31 INFO TaskSchedulerImpl: Killing all running tasks in stage 7: Stage finished
22/10/04 18:03:31 INFO DAGScheduler: Job 7 finished: showString at NativeMethodAccessorImpl.java:0, took 0.124389 s
22/10/04 18:03:31 INFO CodeGenerator: Code generated in 10.286197 ms
22/10/04 18:09:39 INFO BlockManagerInfo: Removed broadcast_7_piece0 on spark-6898f583a42a0257-driver-svc.enterprise-gateway.svc:7079 in memory (size: 5.2 KiB, free: 413.9 MiB)
22/10/04 18:09:39 INFO BlockManagerInfo: Removed broadcast_7_piece0 on 172.18.24.199:39389 in memory (size: 5.2 KiB, free: 413.9 MiB)
[I 2022-10-04 18 (tel:2022100418):24:20,377.377 launch_ipykernel] server_listener got request: {'signum': 2}
[I 2022-10-04 18 (tel:2022100418):24:20,377.377 launch_ipykernel] server_listener got request: {'shutdown': 1}
```

### Observations - 
1. If there is only a driver pod, then the pod gets marked as `succeeded` if the kernel is switched. No matter if it had the executor pods previous attached for doing any tasks. This can be tested by invoking `spark.stop()` at the end of the notebook. `spark.stop()` call is responsible for killing the executor pods.
2. If there are executor pods still running then kernel switch just results in creating a new driver pod for new kernel with **older** **kernel driver and executor pods now in zombie state**

**Comment by kevin-bates** [comment]
@vivekbhide - thanks for opening the issue and the [previous discussion on our Gitter room](https://gitter.im/jupyter/enterprise_gateway?at=633b30a9cb3b243528fb5ece).

Since these process proxies derive directly from [`KubernetesProcessProxy`](https://github.com/jupyter-server/enterprise_gateway/blob/15c6047556733de3e3ef4df94a1985a40a41e514/enterprise_gateway/services/processproxies/k8s.py#L34), it's strange that there's a difference in behavior like this.  Looking at the [`CustomResourceProcessProxy`](https://github.com/jupyter-server/enterprise_gateway/blob/15c6047556733de3e3ef4df94a1985a40a41e514/enterprise_gateway/services/processproxies/crd.py#L14), however, I do see that its implementation of `kill()` should probably be named `terminate_container_resources()`, and override the implementation in `KubernetesProcessProxy` entirely.  This is because the `kill()` method is not always called during the termination of a "kernel". Only when the message-based shutdown of the kernel does not yield results soon enough is the `kill()` method called.  In those "graceful" cases, the container resources are terminated during the `cleanup()` method - which the listener is shutdown, etc.

I suppose this would imply that the normal shutdown scenario is not occurring in a "graceful" manner and, in those cases, `kill()` is called, otherwise we'd see a CRD leak there as well.  Not entirely sure about that theory, but we should definitely rename `kill()` to `terminate_container_resources()` and see where that takes us.

@vivekbhide - are you in a position to give that a try?  If so, I'd like to just include the implementation of `terminate_custom_resource()` into the `terminate_container_resources()` (formerly `kill()`) implementation directly since there isn't another caller of it and it will be confusing having two nearly identically named methods.

**Comment by vivekbhide** [comment]
@kevin-bates - Thank you for analysis. Let me give it a try to see how it behaves. If I understand correctly, then this is what you want me try 
1. rename`kill()` from [CustomResourceProcessProxy](https://github.com/jupyter-server/enterprise_gateway/blob/15c6047556733de3e3ef4df94a1985a40a41e514/enterprise_gateway/services/processproxies/crd.py#L14) to `terminate_container_resources()`
2. include the implementation of `terminate_custom_resource()` into newly renamed `terminate_container_resources()`

Will check and update you on the result.

**Comment by kevin-bates** [comment]
Yes, that is correct.  The second item is more about aesthetics than anything else, so we should have an idea if this is the right track from item 1.

**Comment by vivekbhide** [comment]
@kevin-bates - got it.. and I believe following https://jupyter-enterprise-gateway.readthedocs.io/en/latest/contributors/devinstall.html would be a path to follow for trying these changes ?

**Comment by kevin-bates** [comment]
Yes.  I think `make clean dist enterprise-gateway` should do the trick.  The last of these is what builds the image.  If you find hassles arise due to scala dependencies, let me know and I can build an EG image from your branch if necessary.

**Comment by kevin-bates** [comment]
@vivekbhide - your issue is because you must not have the Spark Operator installed in your k8s config, or its not setup to monitor all namespaces.  If I use [these instructions](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator#installation) to add a `spark-operator` namespace, then I can get past the 404 issue (which I reproduced prior to running the two `helm` commands).  

**We need to improve our docs in this area!** At a minimum, add a link to the "Note" in this section: https://jupyter-enterprise-gateway.readthedocs.io/en/latest/contributors/system-architecture.html#process-proxy

**Comment by vivekbhide** [comment]
@kevin-bates - thanks.. You were right.. I was missing the spark operator and after installing I got past that error too. I will retest the scenario and let you know my result.

**Comment by vivekbhide** [comment]
@kevin-bates - Implementing suggested changes have resolved this issue. I could confirm that, on switching the kernel, the old spark executor pods get deleted, old driver pod goes to `succeeded` state and a new driver pod gets active. Please note that I continue to have `terminate_custom_resource()` as I haven't tested any other scenario and not fully aware of its scope

**Comment by kevin-bates** [comment]
Excellent - thank you for checking that out!

Regarding `terminate_custom_resource()`, it's only used within crd.py and can probably be prefixed with `_` (although I'd prefer it just be incorporated into the `terminate_container_resources()`.

I think we should also update the docs with a link to installing the spark operator and try to detect the issue (and suggest its installation) by trapping that error during the CRD launch - but these can be a separate issue.

I'm away from work yesterday and today (and thru the weekend) but will try to create an issue for this additional work soon.

**Comment by kevin-bates** [comment]
@vivekbhide - are you planning on submitting a pull request to address this issue?  If so, it would be appreciated soon.  Thank you.

**Comment by vivekbhide** [comment]
@kevin-bates - Hi Kevin, Sorry but got held up with something so couldn't do it before. Looks like @kiersten-stokes has already created the PR for this fix so would keep it that way. Thank you @kiersten-stokes

**Comment by kevin-bates** [comment]
Excellent - thank you both!
