### ISSUE TITLE
Conda -> Venv for local development

### ISSUE THREAD

**Issue by bloomsa** [jupyter-server/enterprise_gateway#1294]
### Problem

I'm wondering if there's any appetite for migrating from conda to venv for local development environment setup. I recently began the process in order to try tackling #1089 and I thought it might make more sense to use the [Python endorsed](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment) virtual environment tool as long as we didn't need any specific conda features. It would reduce the barrier to entry for new contributions since more people might be familiar with setting up their virtual environments using that. 
### Proposed Solution

* Rewrite requirements.yml -> requirements.txt
  * this could instead be left off in favor of `pip install .` which seems to be what j[upyter_server](https://github.com/jupyter-server/jupyter_server/blob/main/CONTRIBUTING.rst#installing-the-jupyter-server) and [ipykernel](https://github.com/ipython/ipykernel/blob/main/CONTRIBUTING.md) suggest
* update the Makefile `env` target to use venv rather than conda

### Additional context

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

**Comment by kevin-bates** [comment]
Hi @bloomsa.  I certainly don't have any affinity for a conda environment to do development in.  That said, I don't think we should preclude devs from using either - which you not proposing either.  IMO, the dev should be responsible for ensuring the env in which they are operating is correct, and that is why we removed the forced use of (conda) envs in our `make` targets.  Yes, we left the ability to _create_, _activate_, and _destroy_ (conda) envs, but no other targets perform those actions.

We do, however, recommend the use of conda within our docker images, primarily because a conda installation typically includes a data science stack, so it eases the burden.  That said, most of our images derive from the jupyter docker stacks images, which already provide most of that heavy lifting.

I'm not sure a `requirements.txt` file is necessary since `pip install -e .` should obtain requirements from `pyproject.toml`.  Is that a correct statement?

So, in the end, I don't really see an issue with changing the recommended dev env type from conda to venv.  I will probably stick with mamba as my env "vendor".

I'm curious if @lresende or others have any opinions about this.

**Comment by bloomsa** [comment]
I'm using Mamba too, but I think there is value in "defaulting" to venv for the env `make` targets, reducing the additional "tooling" overhead for new people that may not know about conda/anaconda/mamba/etc. I'm not a python expert but my sense is this "pip install -e . should obtain requirements from pyproject.toml" is true, yes.

**Comment by kevin-bates** [comment]
I think these arguments make good sense Sam - thank you.  We're essentially shortening the ramp for onboarding folks - good stuff.  I'm +1.

**Comment by bloomsa** [comment]
I'll make the PR this weekend. thanks!
