### ISSUE TITLE
JEG not killing ACCEPTED state remote kernels 

### ISSUE THREAD

**Issue by vikasgarg1996** [jupyter-server/enterprise_gateway#719]
Hi Kevin,

I am using Jupyter enterprise gateway with remote kernels. While interrupting JEG, it tries to kill all currently running kernels, but as jupyter client does not return accepted kernels in kernels list, JEG is not sending any signals to those kernels. 

Because of this, even after JEG is not running, remote kernels are present and not being killed.

What can be done regarding this?

## Environment

- Enterprise Gateway Version (Currently working with 1.2, Have not checked with 2.0)
- Platform: YARN
- Python 3

Thanks
Vikas

**Comment by kevin-bates** [comment]
Hi Vikas, thanks for opening this issue in EG (please close the issue in jupyter_client when you get a chance).

I agree this is an issue and is greatly exacerbated by the fact that kernel startups are blocking calls.  Unfortunately, that portion of this issue will likely not be addressed anytime soon due to the multiple layers that require changes (see #580).  Here are some approaches we could take...

First, please take a look at #699.  If your ACCEPTED state is due to the cluster waiting for resources, you might find some relief by leveraging that functionality.

This issue is implying that the application (kernel) has been accepted, but is not yet assigned a host since the host assignment (even if state is still accepted) is what is used to confirm the kernel has "started" - and then is able to be shutdown when JEG is shutdown.  As a result, it sounds like #699 fits this scenario.

However, it's probably a good idea to attempt to shutdown "starting" kernels.  Here are some thoughts...

1. This is really just a YARN issue (one could argue Conductor comes into play as well, but let's focus on YARN).  That said, the solution should be generic relative to RemoteProcessProxy since that's the class we'll likely be using to drive this.
2. ACCEPTED state (in this context) means we have an application ID, but have yet to be assigned a host.  In order to terminate an application, we must have the application ID.
3. I'm thinking we could maintain a global kernel_id to _function_ dict in **`processproxy.py`**, such that those entires only exist when in this particular ACCEPTED state.  I.e., entries enter the dict immediately when appID is obtained, and are removed from the dict immediately when the host is assigned.  Both of these events can be performed within `YarnClusterProcessProxy.confirm_remote_startup()`.  Each process proxy implementation would need to come up with their "location" for where entry/exit of the dict is performed.  
4. The function (lambda), in this case would take kernel_id (for logging), applicationID and yarn endpoint as parameters.  In this case, it would correspond to a class method on YarnClusterProcessProxy that uses the yarn API to terminate an application.  Any other parameters should also be captured when creating the dict entry.
5. We add a `shutdown_starting_kernels()` class method on RemoteProcessProxy.  It will walk the dict values, calling each function.  We could also name the leaf-class function `shutdown_starting_kernels()` although inheritance will not be in play since these are class methods.
6. We add `shutdown()` to enterprisegatewayapp.py such that is first calls the superclass `shutdown()` method (which triggers the shutdown of officially running kernels), then calls `RemoteProcessProxy.shutdown_starting_kernels()`.

I hope that paints a view of what kinds of things need to happen.

**Comment by vikasgarg1996** [comment]
Hi Kevin,
I have closed the issue in Jupyter client as we discussed.

We are already using the changes of #699 as Imam (the guy who has raised that pull request) and me are working together on the same project.

As I was debugging, I found that spark job running remote kernel first goes in "STARTING" state and after receiving the application Id, it goes in "ACCEPTED" state. The time it takes to go to "ACCEPTED" state from "STARTING" state is relatively small. So that might be left.

Your idea of maintaining global kernel id to function dict in **_processproxy_** is really good. But as JEG is single threaded, it can have only one kernel id in "ACCEPTED" state at one time. So we might not need the dictionary. But the dictionary can be fruitful if JEG's going to maintain multiple requests simultaneously.

One more issue I am facing which is creating orphaned Kernels.
Suppose I launch a kernel from jupyter notebooks and JEG is processing the request. The remote kernel is in accepted state and JEG is stuck at "YarnClusterProcessProxy.confirm_remote_startup()".  But if i kill my notebook server now, it doesn't have the kernel id so it will not send any delete kernel request to JEG. And after the kernel comes in running state, JEG sends the kernel id return to notebook server. In this case JEG knows the running kernels but notebook server is not present and I need to kill JEG to kill the remote kernel. 

If i want to use in a service where JEG is running somewhere in a machine and people are connecting to that JEG to launch remote kernels, this might be a big issue.

Thanks
Vikas

**Comment by kevin-bates** [comment]
Hi Vikas, I hope these responses are helpful, please let us know if more information is required or the response isn't answering the correct question...

> But as JEG is single threaded, it can have only one kernel id in "ACCEPTED" state at one time. So we might not need the dictionary. But the dictionary can be fruitful if JEG's going to maintain multiple requests simultaneously.

This isn't quite true.  Applications (kernel) can remain in ACCEPTED state after being assigned a host (meaning that EG believes they are valid, running, kernels).  The state transitions from ACCEPTED to RUNNING when the Spark context is created.  As a result, you _could_ create a kernel with a spark-context-initialization-mode of `none`, in which case, the kernel will remain in ACCEPTED and be able to perform work.  Likewise for those initialization-modes of `lazy`.

That said, we'll get much better throughput once (or should I say, if) async kernel support is added through the stack. 😦 

Yeah, the kernel id's existence in the "accepted-dictionary" should be short-lived nevertheless.

> But if i kill my notebook server now, it doesn't have the kernel id so it will not send any delete kernel request to JEG. And after the kernel comes in running state, JEG sends the kernel id return to notebook server. In this case JEG knows the running kernels but notebook server is not present and I need to kill JEG to kill the remote kernel.

If you know, or can find, the kernel id, you should be able to issue the DELETE request yourself (or build an admin-level app to issue this request).  This is also a good use for idle kernel culling since this kernel will have zero connections in this case.  It's always a good idea to have culling configured with EG, although, depending on your usage requirements, the idle durations may be prohibitive.

**Comment by kevin-bates** [comment]
Closing since this seems related to not having support for asynchronous kernel management - which has existed for a couple of years now.  Should this still be a problem using EG 2.6, we can re-open the issue.
