### ISSUE TITLE
JupyterHub integration with Jupyter Enterprise Gateway (DockerSwarm)

### ISSUE THREAD

**Issue by mihirkapadiap** [jupyter-server/enterprise_gateway#721]
Help us improve the Jupyter Enterprise Gateway project by reporting issues
or asking questions. 

## Description
Trying to integrate JupyterHub with Enterprise Gateway on DockerSwarm.
Can anyone point me steps/wiki/guide.  

## Environment
- Enterprise Gateway
- Platform: DockerSwarm
- JupyterHub

**Comment by kevin-bates** [comment]
@mihirkapadiap - thanks for opening this issue.  Although I'm not familiar how to configure JupyterHub on DockerSwarm, once configured, then configuring the single-user Notebook container to forward its kernel management to the Enterprise Gateway should follow how its done for other environments (on-prem and Kubernetes).

Here are some links that can assist you in that configuration.  However, please note that if your Notebook container is running Notebook 6.0+, you do not need to configure the NB2KG server extension.  Instead, all of those configuration steps can be replaced with adding the Notebook CLI option: `--gateway-url=<url>`.

- Issue #620 covers some setup - relative to kubernetes, but you can extrapolate for Swarm.
- Issue #661 touches on some things, but also includes a link to this [blog post](https://blog.jupyter.org/on-demand-notebooks-with-jupyterhub-jupyter-enterprise-gateway-and-kubernetes-e8e423695cbf).

One thing I would suggest you do first is get Enterprise Gateway working in Swarm w/o Hub.  And Hub working in Swarm w/o EG.  Then connecting the two should be fairly straightforward.  I don't think we've had a lot of airtime on Swarm, so that's where that suggestion is founded.

If you have specific questions relative to JupyterHub, you'll likely get better traction posting your questions to the [JupyterHub discussion forum](https://discourse.jupyter.org/c/jupyterhub/discuss).

**Comment by mihirkapadiap** [comment]
Thanks @kevin-bates for quick reply. 
I did get Enterprise Gateway working on Swarm and tested with single notebook server.
I also got Hub working in Swarm w/o EG (using swarmspawner https://github.com/jupyterhub/dockerspawner)

**Comment by kevin-bates** [comment]
@mihirkapadiap - did you have any luck with getting both Hub and EG working in swarm together?  If not, do you have any further information?  If so, please close this issue and, if possible, provide any additional information others might need to do the same.  Thank you.

**Comment by kevin-bates** [comment]
Closing as it seems the issue/configuration was worked out.
