### ISSUE TITLE
EG support for Spark 3.0.0

### ISSUE THREAD

**Issue by shobhit0511** [jupyter-server/enterprise_gateway#866]
## Description
We are using EG for **Spark 2.3** and **2.4** and we want to move it to **Spark 3.0.0** now so wanted to confirm, If EG existing build can support Spark 3.0.0 as well or it require a new build.

**Comment by kevin-bates** [comment]
No, it cannot.  We are planning our EG 3.0 release to add support for Spark 3.0. Currently, we're tying up loose ends to wrap up EG 2.2, hopefully early next week.

**Comment by sshuklao** [comment]
@kevin-bates any ETA for this.

**Comment by kevin-bates** [comment]
Hi @shobhit0511 - this is tough to say but my guess is at least two weeks.  For one, it requires a new release of Apache Toree (0.5.0) when it's 0.4.0 is just now available.   Likewise, we're just now putting the finishing touches on EG's 2.2.0 release.

There are other things that we want to have in 3.0, some of which update the protocol between the kernel launchers and EG, and those should be in place before 3.0 is available.  But the biggest time-cost is probably provisioning Spark 3.0 environments for testing.  If you're able to help with that, that would be great.

**Comment by ntfrnzn** [comment]
Are there any updates on the timeline or roadmap for Spark 3.0?

**Comment by kevin-bates** [comment]
Hi @ntfrnzn - thanks for the ping on this.  I think it's a matter of getting the 3 pending PRs done.  

@lresende, it looks like #867 is a scala version bump.  Are there other changes relative to the Toree launcher for Spark 3?

I need to get back to #559 and get it running against master (the 3.0 branch).

We should probably merge #877 before anything else.  I'll try to get to that tomorrow.

It would be great if anyone wants to pick up either of #559 or #867 since Luciano and myself are spread fairly thin these days.

**Comment by lresende** [comment]
We would need to have an official Apache Toree release which might take at least a couple of weeks.

**Comment by brenocosta0901** [comment]
@lresende any update about using spark 3 kernels on EG?

**Comment by lresende** [comment]
@brenocosta0901 sorry for dropping the ball here, let me try to get this going over the weekend.

**Comment by amarinderbindra1** [comment]
Hi @lresende, is there any update on the Spark 3 support on Enterprise Gateway? 
Also I see from the PRs mentioned from @kevin-bates, updating the Toree build to the Apache Toree master in Toree Launcher script should be  good enough or will the launcher scripts in the Enterprise Gateway will require changes to communicate with the Spark 3.0 driver/executors launched via the EG?

**Comment by abzymeinsjtu** [comment]
@kevin-bates 

is this case in working progress? seems to be long time after the Pull Request opened.

**Comment by kevin-bates** [comment]
I think both PRs #559 and #867 require attention.  I suspect #559 should be mostly done (although there's probably a good amount of conflict resolutions to deal with) assuming there haven't been changes on the k8s-spark side since that POC was built. 

@lresende will need to respond relative to the Toree status, but I know Luciano has been extremely busy with other responsibilities.

If you're interested, I think wrapping up #559 would be helpful and we could probably add the necessary Toree support as a follow-on since we classify the kernelspec support as "examples".

**Comment by abzymeinsjtu** [comment]
all right

> @lresende will need to respond relative to the Toree status, but I know Luciano has been extremely busy with other responsibilities.

i have recently tested the master branch of Toree and it works fine inside EG, but i'm sure there should be some updates to #867.

**Comment by abzymeinsjtu** [comment]
for toree kernel, seems the spark scala version should be greater than 2.12.14, or a scala compiler problem will occur as mentioned in this issue https://github.com/scala/bug/issues/12019

**Comment by kevin-bates** [comment]
Closing via #559.
